version: '3.8'

services:
  app:
    container_name: app
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: ["yarn", "start:dev"]
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
  db:
    container_name: postgres_container
    image: postgres:14.9-alpine3.18
    restart: unless-stopped
    env_file: ./.env
    environment:
    - POSTGRES_USER=${DB_USERNAME}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_DB=${DB_NAME}
    ports:
    - '5433:5432'
    volumes: 
    - ./.docker/db:/var/lib/postgresql/data
    - ./src/modules/database/init.sql:/docker-entrypoint-initdb.d/db.sql